---
- name: Configure Cisco Nexus Switch - ALL - WITH ROLES
  hosts: all
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: cisco.nxos.nxos

  tasks:
    - import_role:
        name: enable_features

    - import_role:
        name: set_hostname

    - import_role:
        name: create_user

    - import_role:
        name: aaa_config

    - import_role:
        name: ntp_config

    - import_role:
        name: telemetry
        
    - import_role:
        name: write_bck
